"""Adiciona formularios de criacao de OS e Demanda

Revision ID: d2ae9b3a08c7
Revises: d6153c6d18df
Create Date: 2025-08-16 17:06:58.940857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ae9b3a08c7'
down_revision = 'd6153c6d18df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_number', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=120), nullable=False),
    sa.Column('equipment', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('os_type', sa.String(length=20), nullable=False),
    sa.Column('initial_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('os_number')
    )
    with op.batch_alter_table('demands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_order_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parts_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('internal_notes', sa.Text(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'service_orders', ['service_order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demands', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.drop_column('internal_notes')
        batch_op.drop_column('parts_link')
        batch_op.drop_column('service_order_id')

    op.drop_table('service_orders')
    # ### end Alembic commands ###
