"""Adiciona servicos personalizados e acoes de edicao

Revision ID: 2960731a0325
Revises: a9fac98d5ccd
Create Date: 2025-08-16 20:24:59.982348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2960731a0325'
down_revision = 'a9fac98d5ccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_service_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('commission_task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commission_task_id'], ['commission_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_service_items')
    # ### end Alembic commands ###
