"""Criação inicial de todas as tabelas

Revision ID: 2bab3775c949
Revises: 
Create Date: 2025-08-17 02:24:21.659555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bab3775c949'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predefined_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('commission_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_os_number', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('service_type', sa.String(length=50), server_default='Serviço', nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('commission_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('date_completed', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commission_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commission_tasks_external_os_number'), ['external_os_number'], unique=False)

    op.create_table('demands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_service_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('commission_task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commission_task_id'], ['commission_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('demand_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demand_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_services_association',
    sa.Column('commission_task_id', sa.Integer(), nullable=False),
    sa.Column('predefined_service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commission_task_id'], ['commission_tasks.id'], ),
    sa.ForeignKeyConstraint(['predefined_service_id'], ['predefined_services.id'], ),
    sa.PrimaryKeyConstraint('commission_task_id', 'predefined_service_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_services_association')
    op.drop_table('demand_logs')
    op.drop_table('custom_service_items')
    op.drop_table('notes')
    op.drop_table('demands')
    with op.batch_alter_table('commission_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commission_tasks_external_os_number'))

    op.drop_table('commission_tasks')
    op.drop_table('users')
    op.drop_table('predefined_services')
    # ### end Alembic commands ###
