"""Adiciona service_type a commission_tasks

Revision ID: 68efec225e2e
Revises: 41032d055e98
Create Date: 2025-08-16 19:35:32.724551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68efec225e2e'
down_revision = '41032d055e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commission_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_type', sa.String(length=50), server_default='Serviço', nullable=False))

    with op.batch_alter_table('demand_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('demand_logs_demand_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'demands', ['demand_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('demand_logs_demand_id_fkey'), 'demands', ['demand_id'], ['id'])

    with op.batch_alter_table('commission_tasks', schema=None) as batch_op:
        batch_op.drop_column('service_type')

    # ### end Alembic commands ###
