"""Adiciona servicos pre-definidos com pesos

Revision ID: a9fac98d5ccd
Revises: 68efec225e2e
Create Date: 2025-08-16 20:01:23.775861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9fac98d5ccd'
down_revision = '68efec225e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predefined_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('task_services_association',
    sa.Column('commission_task_id', sa.Integer(), nullable=False),
    sa.Column('predefined_service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commission_task_id'], ['commission_tasks.id'], ),
    sa.ForeignKeyConstraint(['predefined_service_id'], ['predefined_services.id'], ),
    sa.PrimaryKeyConstraint('commission_task_id', 'predefined_service_id')
    )
    with op.batch_alter_table('commission_tasks', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commission_tasks', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    op.drop_table('task_services_association')
    op.drop_table('predefined_services')
    # ### end Alembic commands ###
